### ISSUE TITLE
Fail to reset password via HikariConfigMXBean at runtime!!!

### ISSUE THREAD

**Issue by yuanpli** [brettwooldridge/HikariCP#1137]
## Environment
```
HikariCP version: 3.1.0
JDK version     : 1.8.0_161
Database        : Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
Driver version  : ojdbc7 12.1.0.1
```
#### DataSource
```java
HikariDataSource dataSource = new HikariDataSource();
            dataSource.setMaximumPoolSize(40);
            dataSource.setUsername(user);
            dataSource.setPassword(password);
            dataSource.setDriverClassName(driverClassName);
            dataSource.setRegisterMbeans(true);
            dataSource.setJdbcUrl(url);
```
#### Reset Password
```java
HikariDataSource hikariDataSource = (HikariDataSource) dataSource;
hikariDataSource.getHikariConfigMXBean().setPassword("newPassword");
hikariDataSource.getHikariPoolMXBean().softEvictConnections();
```

Seems that new username and password are not set into **driverProperties** when calling function `getConnection(String username, String password)` in class **DriverDataSource**. 

```java 
   @Override
   public Connection getConnection(String username, String password) throws SQLException
   {
      return getConnection();
   }
```

It works in my testing after changed above code to 
```java
   @Override
   public Connection getConnection(String username, String password) throws SQLException
   {
      if (username != null) {
         driverProperties.put("user", username);
      }
      if (password != null) {
         driverProperties.put("password", password);
      }
      return getConnection();
   }
```
Hi @brettwooldridge,
Could you kindly share your comment? Thanks!

**Comment by yuanpli** [comment]
Any update for this issue? Is it a known issue? Is there any plan/schedule when it will be fixed?

**Comment by brettwooldridge** [comment]
I’ll take a look.  I don’t have the code in front of me but it’s possible that the password change is only wired through for our DataSources and not wrapped driver DataSources.

**Comment by 2ndalpha** [comment]
Unfortunately it does not work for me.
The code is in Kotlin but it should not make a difference.
Is it PostgreSQL specific issue or I'm missing something here?

```kotlin
val dataSource = HikariDataSource()
dataSource.driverClassName = "org.postgresql.Driver"
dataSource.jdbcUrl = "jdbc:postgresql://myserver/mydatabase"
dataSource.username = "myuser"
dataSource.password = "validpassword"

Timer().schedule(10_000, 10_000) {
  dataSource.hikariConfigMXBean.setPassword("incorrect")
  dataSource.hikariPoolMXBean.softEvictConnections()
}
```

**Comment by thakur-mohit** [comment]
Hi . I am trying to reset password at runtime. Below is the application.yaml configuration. I have set registermbeans =true
What other code changes i need to make. kindly share some example. 
spring:
  datasource:
    hikari:
              connection-timeout: 70000
              maximum-pool-size: 2
              minimum-idle: 1
              register-mbeans: true
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

**Comment by yichuan-hpe** [comment]
Has this issue been fixed and released? which version?

**Comment by lfbayer** [comment]
Fixed with "HikariCP-3.2.0". Clicking on the [link (851e2d4)](https://github.com/brettwooldridge/HikariCP/commit/851e2d4592b52a9c367ada2c76f013b1d4e20ac3) for the commit will show the tag/branch it is in.

**Comment by yichuan-hpe** [comment]
I tested against 3.4.5 and 4.0.3, still see the issue. I am using scala, but the code is doing the same as above.
