### ISSUE TITLE
Default Isolation Level selection with MariaDB, and Galera

### ISSUE THREAD

**Issue by bcabbott** [brettwooldridge/HikariCP#821]
Hi

First of all, thanks for a great library, and apologies for the long post.

Background:
We are using Hikari 2.5.1, along with MariaDB and Galera, a multi-master database.  For this description, the MariaDB JDBC library is pointing at a single DB node.  I have come across an issue where no connections ever get added to the pool, and wanted to hear your opinion.  I am unsure if Hikari is at fault, MariaDB JDBC, or both to some degree.

When the MariaDB service is started, the DB engine has to determine if the node has the latest data.  If it is only slightly behind, it performs an Incremental State Transfer (IST) - i.e. changes.  If it is significantly behind, it performs a Snapshot State Transfer (SST) - i.e. backup and restore, followed by an IST stage.
During SST the server is off, and no connection can be made.  During IST, the server can be connected to, but the majority of SQL fails.

Our application was started first, followed by the DB server.  The application layer, through our own external methods, know the DB is not available, so does not call "getConnection" on the Hikari Datasource.  The pool however attempts to populate the pool.

Issue:
PoolBase.java checkDriverSupport(), determines the driver's defaultIsolationLevel on the first connection.  In the scenario above, MariaDB JDBC throws an Exception.  Hikari catches the exception and logs a warning, defaultTransactionIsolation remains 0 (int default value), and transactionIsolation remains = -1.  (We have not configured Hikari with a value).  This code will not be run again.

After this call, in setupConnection(), defaultTransactionIsolation <> transactionIsolation, and so it is attempted to be set on all newly created connections.  setTransactionIsolation(-1) is passed, however -1 is not a valid value for isolation level.

We have worked around the bug, by configuring a defaultTransactionIsolation.
One could also argue that:
a) Perhaps MariaDB JDBC "isValid" should not be returning true.
The counter argument is, that the connection is alive, and certain administrative SQL calls can be made.  (We do this with a management application we have, admitedly though without Hikari).
b) We use a ConnectionTestQuery
both of the above would not cause the isValidChecked to be set to true.

**Comment by brettwooldridge** [comment]
@bcabbott If you are capable of setting a breakpoint in the code [here](https://github.com/brettwooldridge/HikariCP/blob/HikariCP-2.5.1/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L418), I would like to know what the ``SQLException..getSQLState()`` and ``SQLException.getErrorCode()`` return values are.

**Comment by bcabbott** [comment]
Thanks for the prompt response.

I will have a go at replicating early next week, when back in the office.  I will also get the values for a similar scenario, when the Galera cluster is "split brain", and we are connecting to the non primary segment of the cluster.

Thanks
Brendon

**Comment by bcabbott** [comment]
Hello again
In the last half hour, I have managed to quickly run the test of split brain, as this can be replicated by simply removing network cables.  This gives the same behaviour, but there may be different error codes/messages.

So, in the split brain scenario, the exception is:
Message: WSREP has not yet prepared node for application use\nQuery is : SELECT @@tx_isolation
SQLState: 08S01
ErrorCode: 1047

https://mariadb.com/kb/en/mariadb/mariadb-error-codes/ lists this as a generic error of "Unknown Command" - so not very useful, given the SQL *is* a valid command.

Whilst testing this, I have made a separate TestCase separate from our J2EE application.  Whilst doing this, I have realised that we have Hikari's InitializationFailFast = false.  With this set to true, the pool does not get created.

I will continue setting up the system to try and replicate a long IST, and hence capture the error codes for this scenario.  My suspicion is that they are going to be the same values.

**Comment by brettwooldridge** [comment]
Fixed by commit 1a6dc21.

**Comment by bcabbott** [comment]
Thankyou for the prompt fix, we will incorporate this fix once it is released, and when we schedule in upgrading to the 2.6.x series of Hikari.

We did carry out the original tests, creating the pool during an IST.  I can confirm that this produces exactly the same SQL exception, code and message, as the Galera "split-brain" condition described above.

Thanks again
Brendon

**Comment by guogl** [comment]
@brettwooldridge We are using the 3.4.1 HikariCP version, but we are still experiencing this issue. The database is the mysql8, mysql connector version is 8.0.25
At the beginning, we experienced the below error:
`db_9 - Default transaction isolation level detection failed (Communications link failure
The last packet successfully received from the server was 10,007 milliseconds ago. The last packet sent successfully to the server was 10,007 milliseconds ago.).`

After that, our application keep getting the below errors:
`Caused by: java.sql.SQLException: Unsupported transaction isolation level '-1'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ConnectionImpl.setTransactionIsolation(ConnectionImpl.java:2257)
	at com.mysql.cj.jdbc.ha.MultiHostMySQLConnection.setTransactionIsolation(MultiHostMySQLConnection.java:560)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.mysql.cj.jdbc.ha.FailoverConnectionProxy.invokeMore(FailoverConnectionProxy.java:530)
	at com.mysql.cj.jdbc.ha.MultiHostConnectionProxy.invoke(MultiHostConnectionProxy.java:513)
	at com.sun.proxy.$Proxy51.setTransactionIsolation(Unknown Source)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:405)
	... 10 common frames omitted`

After restart the application, the error disappeared.
